spring:
  application:
    name: activiti-learning-example
  datasource:
    url: jdbc:mysql://localhost:3306/trace_anywhere_test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
